### PR TITLE
Remove parent from root pom.xml so we can do a mvn versions:set on this project

### PR DESCRIPTION
**Pull request by cunningt**
I'd like to remove the parent from the root pom.xml so that we can do a mvn versions:set at the root directory and so it builds okay within our pipeline.

I don't think there's any issue with doing that - the other modules (core/tests) both use parent as a parent.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Not sure this is really the correct way for a kafka connector. Usually they have a parent pom. @valdar9 wdyt?

**Comment by cunningt** [comment]
I'm not removing the parent - core (https://github.com/jboss-fuse/camel-kafka-connector/blob/master/core/pom.xml#L4-L9) and tests (https://github.com/jboss-fuse/camel-kafka-connector/blob/master/tests/pom.xml#L25-L30) both use it as a parent.     The only thing I'm doing here is removing it from the root pom.xml so that we can cleanly do a versions:set.

**Comment by oscerd** [comment]
Yeah, I was from mobile. Sorry

**Review by oscerd — APPROVED** [review]

**Comment by cunningt** [comment]
No problem - it'd just save a bunch of work with having to cover this sort of case in the pipeline.      Thanks for the review!

**Review by valdar — COMMENTED** [review]
LGTM

**Pull request merged**
